swagger: "2.0"
info:
  host: idmatch.co
  description: Document recognition based on OpenCV
  title: Go-idmatch
  contact:
    name: Mad Devs
    email: rock@maddevs.io
    url: https://idmatch.co
consumes:
- multipart/form-data
produces:
- application/json
schemes:
- https
paths:
  /ocr:
    post:
      summary: Send document image to recognition engine
      parameters:
        - in: formData
          name: id
          description: Document image
          required: true
          type: file
          examples:
              cat:  # <--- example name
                summary: An example of a cat
                externalValue: http://api.example.com/examples/cat.json
      responses:
        200:
          description: JSON with recognized text
          content:
            application/json:
          schema:
            $ref: "#/definitions/item"
        default:
          description: generic error response
          content:
            application/json:
          schema:
            $ref: "#/definitions/error"
definitions:
  item:
    type: object
    properties:
      firstname:
        type: string
      surname:
        type: string
      middlename:
        type: string
      serial:
        type: string
      birthday:
        type: string
      gender:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string